# -*- coding: utf-8 -*-
"""Ganaderia bovina .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QKgaQhoWk68zdspFqjD0IYd3cRyD_Nlv
"""

import pandas as pd
from pyspark.sql import SparkSession

# Asegurar que SparkSession esté disponible y activa
# Se detiene cualquier sesión existente para evitar conflictos y se crea una nueva.
if 'spark' in locals() and spark.sparkContext._jsc is not None:
    spark.stop()

spark = SparkSession.builder \
    .appName("BigDataCarneBovina") \
    .getOrCreate()

print("SparkSession creada exitosamente.")

# Cargar el archivo CSV usando pandas
pd_df = pd.read_csv("//content/Base_14000_Datos.csv")

# Convertir el DataFrame de pandas a un DataFrame de PySpark
df = spark.createDataFrame(pd_df)

print("DataFrame de PySpark creado exitosamente desde pandas.")

print("\nCantidad de registros (desde pandas a PySpark):")
print(df.count())

print("\nEstructura de datos (desde pandas a PySpark):")
df.printSchema()

print("\nPrimeros registros (desde pandas a PySpark):")
df.show(5)

from pyspark.sql.types import DateType, DoubleType, IntegerType
from pyspark.sql.functions import regexp_replace, col, trim, when, lit, isnull, length

# Convertir la columna 'fecha' a tipo DateType
df = df.withColumn("fecha", df["fecha"].cast(DateType()))

# Convertir 'precio_kg', 'ventas', 'temperatura' a IntegerType si son String/Double
df = df.withColumn("precio_kg", df["precio_kg"].cast(IntegerType()))
df = df.withColumn("ventas", df["ventas"].cast(IntegerType()))
df = df.withColumn("temperatura", df["temperatura"].cast(IntegerType()))

# Limpiar la columna 'inflacion' (trim, reemplazar comas por puntos) y luego convertir a DoubleType de forma robusta
cleaned_inflacion_col = regexp_replace(trim(col("inflacion")), ",", ".")

# Patrón regex para verificar si la cadena limpia es un número válido (ej. "123", "-45.67", ".5", "0.5")
# Esto evita errores al intentar castear cadenas no numéricas como "N/A" o vacías.
valid_double_pattern = r"^[+-]?(\d+(\.\d*)?|\.\d+)$"

df = df.withColumn(
    "inflacion",
    when(
        isnull(col("inflacion")) | (length(trim(col("inflacion"))) == 0), # Si es nulo o cadena vacía original
        lit(None).cast(DoubleType())
    ).when(
        cleaned_inflacion_col.rlike(valid_double_pattern), # Si después de limpiar es un número válido
        cleaned_inflacion_col.cast(DoubleType())
    ).otherwise(
        lit(None).cast(DoubleType()) # Si no es un número válido (ej. "N/A", "abc")
    )
)

df.cache()
df.count()

print("Estructura de datos después de la conversión de tipos:")
df.printSchema()

# Verificar si hay valores nulos en la columna 'inflacion' después de la limpieza robusta
print("Valores nulos en 'inflacion' después de la limpieza robusta:", df.filter(col("inflacion").isNull()).count())

# Contar valores nulos por columna
print("Conteo de valores nulos por columna:")
for col in df.columns:
    print(f"Columna '{col}': {df.filter(df[col].isNull()).count()}")

# Estrategia de manejo de nulos (ej: rellenar con la media para numéricas, o con un valor 'desconocido' para categóricas)
# Para este dataset simulado, si no hay nulos, esta sección es para fines demostrativos.
# Si hubiera nulos en 'inflacion', podríamos rellenar con la media:
# from pyspark.sql.functions import mean
# mean_inflacion = df.select(mean(df['inflacion'])).collect()[0][0]
# df = df.na.fill(mean_inflacion, subset=['inflacion'])

# En este caso, no hay nulos, por lo que este paso se omite en la ejecución pero se muestra como ejemplo.

from pyspark.sql.functions import year, month, dayofmonth, dayofweek

# Extraer año, mes, día del mes y día de la semana de la columna 'fecha'
df = df.withColumn("anio", year(df["fecha"])) \
       .withColumn("mes", month(df["fecha"])) \
       .withColumn("dia_mes", dayofmonth(df["fecha"])) \
       .withColumn("dia_semana", dayofweek(df["fecha"])) # 1 = Domingo, 7 = Sábado

print("Estructura de datos después de ingeniería de características:")
df.printSchema()
print("\nPrimeros registros con nuevas características:")
df.cache() # Cache the DataFrame to stabilize its state before showing
df.show(5)

from pyspark.ml.feature import VectorAssembler, StringIndexer
from pyspark.ml.regression import RandomForestRegressor
from pyspark.ml.evaluation import RegressionEvaluator
from pyspark.sql.functions import col

# Identificar columnas categóricas y numéricas
categorical_cols = ["estado", "producto", "mercado", "tipo_alimentacion", "demanda", "oferta"]
numerical_cols = ["inflacion", "temperatura", "ventas", "anio", "mes", "dia_mes", "dia_semana"]

# --- Pipeline de Preprocesamiento ---
# 1. Indexar columnas categóricas
indexed_df = df
for col_name in categorical_cols:
    indexer = StringIndexer(inputCol=col_name, outputCol=col_name + "_indexed")
    indexed_df = indexer.fit(indexed_df).transform(indexed_df)

# Actualizar la lista de columnas de características incluyendo las indexadas
feature_cols = [col_name + "_indexed" for col_name in categorical_cols] + numerical_cols

# 2. Ensamblar características en un solo vector
vector_assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features"
)

# Aplicar el ensamblador al DataFrame
final_df = vector_assembler.transform(indexed_df)

# 3. Dividir los datos en conjuntos de entrenamiento y prueba
(training_data, test_data) = final_df.randomSplit([0.8, 0.2], seed=42)

print("Datos de entrenamiento:", training_data.count())
print("Datos de prueba:", test_data.count())

# Mostrar el esquema del DataFrame final con la columna de características
print("\nEsquema del DataFrame final:")
final_df.printSchema()

# Mostrar los primeros registros con la columna de características
print("\nPrimeros registros con columna 'features':")
final_df.select("fecha", "precio_kg", "features").show(5, truncate=False)

# Crear el modelo de Random Forest Regressor
rf = RandomForestRegressor(featuresCol="features", labelCol="precio_kg", numTrees=100, seed=42)

# Entrenar el modelo
rf_model = rf.fit(training_data)

# Realizar predicciones en el conjunto de prueba
predictions = rf_model.transform(test_data)

# Mostrar algunas predicciones y los valores reales
print("\nPredicciones del modelo de Random Forest:")
predictions.select("fecha", "precio_kg", "prediction").show(10, truncate=False)

# Evaluar el modelo
evaluator = RegressionEvaluator(labelCol="precio_kg", predictionCol="prediction", metricName="mae")
mae = evaluator.evaluate(predictions)

print(f"\nError Absoluto Medio (MAE) en el conjunto de prueba: {mae:.2f}")

evaluator_rmse = RegressionEvaluator(labelCol="precio_kg", predictionCol="prediction", metricName="rmse")
rmse = evaluator_rmse.evaluate(predictions)

print(f"Raíz del Error Cuadrático Medio (RMSE) en el conjunto de prueba: {rmse:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

print("\nGenerando gráfica de rendimiento del modelo...")

# 1. Seleccionar una muestra de las predicciones y ordenarlas por fecha
# Convertimos a Pandas solo las columnas necesarias para no saturar la memoria
df_grafica = predictions.select("fecha", "precio_kg", "prediction") \
                        .orderBy("fecha") \
                        .limit(200) \
                        .toPandas() # Convertir a pandas para graficar

# 2. Configurar el estilo de la gráfica
plt.figure(figsize=(12, 6))
sns.set_theme(style="whitegrid")

# 3. Dibujar las líneas de precio Real vs Predicho
plt.plot(df_grafica['fecha'], df_grafica['precio_kg'], label='Precio Real (Kg)', color='royalblue', linewidth=2, marker='o', markersize=4)
plt.plot(df_grafica['fecha'], df_grafica['prediction'], label='Predicción del Modelo', color='darkorange', linewidth=2, linestyle='--', marker='x', markersize=4)

# 4. Personalizar títulos y etiquetas
plt.title('Comparativa: Precio Real vs Predicción de Carne Bovina (Muestra de 200 datos)', fontsize=14, fontweight='bold')
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Precio por Kilogramo', fontsize=12)
plt.xticks(rotation=45)
plt.legend(fontsize=11)

# 5. Mostrar la gráfica de manera limpia
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, create_map, regexp_replace, trim, when, isnull, length
from pyspark.sql.types import IntegerType, DoubleType

# Componentes de Machine Learning de PySpark
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml.regression import LinearRegression, DecisionTreeRegressor, GBTRegressor
from pyspark.ml.clustering import KMeans
from pyspark.ml.fpm import FPGrowth  # Alternativa nativa y eficiente a Apriori en Spark
from pyspark.ml.evaluation import RegressionEvaluator


# INICIALIZAR SPARK SEESION

if 'spark' in locals() and spark.sparkContext._jsc is not None:
    spark.stop()

spark = SparkSession.builder \
    .appName("MineriaDatosCarneBovina") \
    .getOrCreate()

print("SparkSession creada exitosamente.")


# CARGAR Y PREPARAR BASE DE DATOS

# Usamos pandas temporalmente para leer el Excel
pd_df = pd.read_csv("/content/Base_14000_Datos.csv")
df = spark.createDataFrame(pd_df)

# Asegurar tipos numéricos correctos
df = df.withColumn("precio_kg", col("precio_kg").cast(IntegerType())) \
       .withColumn("temperatura", col("temperatura").cast(IntegerType())) \
       .withColumn("ventas", col("ventas").cast(IntegerType()))

# Limpiar la columna 'inflacion' (trim, reemplazar comas por puntos) y luego convertir a DoubleType de forma robusta
cleaned_inflacion_col = regexp_replace(trim(col("inflacion")), ",", ".")

# Patrón regex para verificar si la cadena limpia es un número válido (ej. "123", "-45.67", ".5", "0.5")
valid_double_pattern = r"^[+-]?(\d+(\.\d*)?|\.\d+)$"

df = df.withColumn(
    "inflacion",
    when(
        isnull(col("inflacion")) | (length(trim(col("inflacion"))) == 0), # Si es nulo o cadena vacía original
        lit(None).cast(DoubleType())
    ).when(
        cleaned_inflacion_col.rlike(valid_double_pattern), # Si después de limpiar es un número válido
        cleaned_inflacion_col.cast(DoubleType())
    ).otherwise(
        lit(None).cast(DoubleType()) # Si no es un número válido (ej. "N/A", "abc")
    )
)

# CONVERTIR VARIABLES CATEGÓRICAS (StringIndexer)

categorical_cols = ['estado', 'producto', 'mercado', 'tipo_alimentacion', 'demanda', 'oferta']
numerical_cols = ['inflacion', 'temperatura', 'ventas']

indexed_df = df
for col_name in categorical_cols:
    indexer = StringIndexer(inputCol=col_name, outputCol=col_name + "_indexed", handleInvalid="keep")
    indexed_df = indexer.fit(indexed_df).transform(indexed_df)


# VARIABLES DE ENTRADA Y SALIDA (VectorAssembler)

feature_cols = [c + "_indexed" for c in categorical_cols] + numerical_cols

assembler = VectorAssembler(inputCols=feature_cols, outputCol="features")
final_df = assembler.transform(indexed_df)

# Dividir datos en Entrenamiento (80%) y Prueba (20%)
(training_data, test_data) = final_df.randomSplit([0.8, 0.2], seed=42)
training_data.cache()
test_data.cache()

# Evaluador común para MAE
evaluator_mae = RegressionEvaluator(labelCol="precio_kg", predictionCol="prediction", metricName="mae")


# 1. REGRESIÓN LINEAL

print("\n==============================")
print("REGRESIÓN LINEAL")
print("==============================")
lr = LinearRegression(featuresCol="features", labelCol="precio_kg")
lr_model = lr.fit(training_data)
pred_regresion = lr_model.transform(test_data)
mae_regresion = evaluator_mae.evaluate(pred_regresion)
print(f"MAE Regresión: {mae_regresion:.2f}")


# 2. ÁRBOL DE DECISIÓN

print("\n==============================")
print("ÁRBOL DE DECISIÓN")
print("==============================")
dt = DecisionTreeRegressor(featuresCol="features", labelCol="precio_kg", maxDepth=5, seed=42)
dt_model = dt.fit(training_data)
pred_arbol = dt_model.transform(test_data)
mae_arbol = evaluator_mae.evaluate(pred_arbol)
print(f"MAE Árbol: {mae_arbol:.2f}")


# 3. GRADIENT-BOOSTED TREES (Alternativa Robusta a Redes en Spark)

print("\n==============================")
print("GRADIENT-BOOSTED TREES (MLP ALTERNATIVE)")
print("==============================")
# Nota: MLPRegressor en Spark es solo para clasificación. Para regresión compleja
# en Big Data se utilizan árboles optimizados (GBT), que suelen ser más estables.
gbt = GBTRegressor(featuresCol="features", labelCol="precio_kg", maxIter=50, seed=42)
gbt_model = gbt.fit(training_data)
pred_gbt = gbt_model.transform(test_data)
mae_gbt = evaluator_mae.evaluate(pred_gbt)
print(f"MAE GBT (Patrones Complejos): {mae_gbt:.2f}")


# 4. CLUSTERING (K-MEANS)

print("\n==============================")
print("CLUSTERING (K-MEANS)")
print("==============================")
kmeans = KMeans(featuresCol="features", k=3, seed=42, predictionCol="cluster")
kmeans_model = kmeans.fit(final_df)
clustered_df = kmeans_model.transform(final_df)

print("Clusters generados (Muestra):")
clustered_df.select("precio_kg", "cluster").show(5)


# 5. REGLAS DE ASOCIACIÓN (FP-GROWTH)

print("\n==============================")
print("REGLAS DE ASOCIACIÓN")
print("==============================")
# Apriori es ineficiente en Big Data. Usamos FP-Growth, que hace lo mismo pero 100x más rápido.
# Creamos la estructura de canasta/transacción agrupando las columnas categóricas en un array de texto
from pyspark.sql.functions import array
df_items = df.withColumn("items", array(col("producto"), col("mercado"), col("demanda")))

fp_growth = FPGrowth(itemsCol="items", minSupport=0.1, minConfidence=0.5)
fp_model = fp_growth.fit(df_items)

print("Primeras reglas de asociación encontradas:")
fp_model.associationRules.select("antecedent", "consequent", "support", "confidence").show(5, truncate=False)


# COMPARACIÓN DE MODELOS Y CONCLUSIONES

print("\n==============================")
print("COMPARACIÓN DE MODELOS")
print("==============================")
print(f"Regresión Lineal: {mae_regresion:.2f}")
print(f"Árbol de Decisión: {mae_arbol:.2f}")
print(f"Gradient-Boosted Trees: {mae_gbt:.2f}")

print("\n==============================")
print("CONCLUSIONES")
print("==============================")
print("- La regresión identifica relaciones lineales básicas.")
print("- El árbol de decisión estructura reglas claras de decisión.")
print("- GBT se encarga de las interacciones no lineales y complejas de los datos.")
print("- K-Means segmentó la base de datos en 3 grupos de comportamiento.")
print("- FP-Growth descubrió qué combinaciones de producto-mercado-demanda ocurren juntas.")


# 📊 GENERACIÓN DE GRÁFICA COMPARATIVA

print("\nGenerando gráfica comparativa de modelos...")

# Tomamos una pequeña muestra de prueba ordenada para evitar saturar la gráfica
# Usamos el modelo de Árbol de Decisión como base de predicción visual
df_plot = pred_arbol.select("precio_kg", "prediction").limit(100).toPandas()

plt.figure(figsize=(14, 6))
sns.set_theme(style="whitegrid")

# Línea de valores reales
plt.plot(df_plot.index, df_plot['precio_kg'], label='Precio Real (Kg)',
         color='#2b5c8f', linewidth=2, marker='o', markersize=4)

# Línea de valores predichos
plt.plot(df_plot.index, df_plot['prediction'], label='Predicción (Árbol de Decisión)',
         color='#e67e22', linewidth=2, linestyle='--', marker='x', markersize=4)

plt.title('Rendimiento del Modelo en PySpark: Valores Reales vs Predicciones', fontsize=14, fontweight='bold')
plt.xlabel('Índice de Muestra (Primeros 100 registros de prueba)', fontsize=12)
plt.ylabel('Precio ($ / Kg)', fontsize=12)
plt.legend(fontsize=11, loc='upper right')

plt.tight_layout()
plt.show()

import pandas as pd
from sklearn.tree import DecisionTreeRegressor, export_text

df = pd.read_csv("/content/Base_14000_Datos.csv") # Datos ya cargados en la celda inicial.

print(df.head())

# Estado de las variables: 'estado' y 'mercado' ya son numéricas; 'producto' tiene One-Hot Encoding.
# Solo se aplica Codificación de Etiquetas (Label Encoding) a 'tipo_alimentacion'.
if 'tipo_alimentacion' in df.columns and df['tipo_alimentacion'].dtype == 'object':
    df['tipo_alimentacion'] = df['tipo_alimentacion'].astype('category').cat.codes

# Incluir: 'producto', 'estado', 'mercado', 'tipo_alimentacion' (codificadas) junto con 'demanda' y 'oferta' (One-Hot).
# Excluir: 'precio_kg' (variable objetivo) y 'fecha'.
features_to_exclude = ['precio_kg', 'fecha']
X = df.drop(columns=features_to_exclude)
y = df['precio_kg']

# Corrección de ValueError: Asegurar que todas las columnas en X sean numéricas.
# Se trabaja sobre una copia de 'df' para aislar el preprocesamiento de este modelo
df_processed_for_dt = df.copy()

# Preprocesar la columna 'inflacion' para asegurar que sea numérica
# Reemplazar comas por puntos y convertir a numérico, manejando errores
if 'inflacion' in df_processed_for_dt.columns:
    df_processed_for_dt['inflacion'] = df_processed_for_dt['inflacion'].astype(str).str.replace(',', '.', regex=False)
    df_processed_for_dt['inflacion'] = pd.to_numeric(df_processed_for_dt['inflacion'], errors='coerce')

# Garantizar que 'tipo_alimentacion' sea numérica (conversión condicional por robustez)
if 'tipo_alimentacion' in df_processed_for_dt.columns and df_processed_for_dt['tipo_alimentacion'].dtype == 'object':
    df_processed_for_dt['tipo_alimentacion'] = df_processed_for_dt['tipo_alimentacion'].astype('category').cat.codes

# Estas columnas fueron identificadas como que tienen valores de cadena: 'estado', 'producto', 'mercado', 'demanda', 'oferta'.
categorical_cols_to_onehot = ['estado', 'producto', 'mercado', 'demanda', 'oferta']
# Filtrar para incluir solo las columnas que son de tipo 'object' y existen en el DataFrame.
categorical_cols_to_onehot = [
    col for col in categorical_cols_to_onehot
    if col in df_processed_for_dt.columns and df_processed_for_dt[col].dtype == 'object'
]

if categorical_cols_to_onehot:
    # Aplicar one-hot encoding. `drop_first=True` ayuda a evitar la multicolinealidad.
    df_processed_for_dt = pd.get_dummies(df_processed_for_dt, columns=categorical_cols_to_onehot, drop_first=True)

# Definir características (X) y objetivo (y) del DataFrame recién preprocesado.
X = df_processed_for_dt.drop(columns=['precio_kg', 'fecha'])
y = df_processed_for_dt['precio_kg']

# Ahora ajustar el modelo de Regresor de Árbol de Decisión con las características codificadas numéricamente.
modelo = DecisionTreeRegressor(max_depth=4, random_state=42)
modelo.fit(X, y)

print(export_text(modelo, feature_names=X.columns.tolist()))

df['precio_predicho'] = modelo.predict(X)

print(df.head())

import numpy as np
import pandas as pd # Asegurar que pandas esté importado si no está disponible globalmente

# Obtener los nombres de las características de los datos de entrenamiento X (del modelo de Árbol de Decisión en XBeS-TM-2ID1)
feature_columns = X.columns.tolist()

# Crear un nuevo DataFrame para la predicción con las mismas columnas que X, inicializado a 0
nuevos_datos_processed = pd.DataFrame(0, index=range(3), columns=feature_columns)

# Entrada original para nuevos puntos de datos
# Nota: Se asume que los IDs numéricos originales para estado, mercado, producto_id, tipo_alimentacion
# necesitan ser mapeados de vuelta a categorías de cadena para una codificación one-hot adecuada.
# Se añaden valores predeterminados para 'demanda' y 'oferta', ya que faltan en original_nuevos_datos.
original_nuevos_datos = pd.DataFrame({
    'estado_id':[0,3,5], # Renombrado para evitar confusión con la cadena 'estado'
    'producto_id':[1,2,0],
    'mercado_id':[2,1,0], # Renombrado para evitar confusión con la cadena 'mercado'
    'tipo_alimentacion':[1,2,0],
    'demanda':['media', 'media', 'media'], # Valores predeterminados añadidos como cadenas para codificación one-hot
    'oferta':['media', 'media', 'media']   # Valores predeterminados añadidos como cadenas para codificación one-hot
})


# Mapeo de estado (inferido basándose en estados comunes y posible asignación arbitraria de ID)
estado_map = {
    0: 'Puebla', 1: 'Chiapas', 2: 'CDMX', 3: 'Jalisco', 4: 'Mexico',
    5: 'Michoacan', 6: 'Nuevo León', 7: 'Oaxaca', 8: 'Sonora',
    9: 'Tabasco', 10: 'Veracruz', 11: 'Yucatan', 12: 'Guanajuato', 13: 'Coahuila'
}
# Mapear estado_id a la cadena 'estado'
original_nuevos_datos['estado'] = original_nuevos_datos['estado_id'].map(estado_map).fillna('Puebla') # Usar un valor predeterminado si el mapeo falla

# Mapeo de mercado
mercado_map = {
    0: 'central_abasto', 1: 'digital', 2: 'supermercado', 3: 'tradicional'
}
# Mapear mercado_id a la cadena 'mercado'
original_nuevos_datos['mercado'] = original_nuevos_datos['mercado_id'].map(mercado_map).fillna('supermercado')

# Mapeo de producto (para codificación one-hot, esta es la versión de cadena)
producto_string_map = {
    0: 'arrachera', 1: 'bistec', 2: 'carne_molida'
}
# Mapear producto_id a la cadena 'producto'
original_nuevos_datos['producto'] = original_nuevos_datos['producto_id'].map(producto_string_map)

# Crear un DataFrame temporal con todas las cadenas categóricas y 'tipo_alimentacion' codificado con etiquetas
temp_df_for_ohe = pd.DataFrame({
    'estado': original_nuevos_datos['estado'],
    'producto': original_nuevos_datos['producto'],
    'mercado': original_nuevos_datos['mercado'],
    'demanda': original_nuevos_datos['demanda'],
    'oferta': original_nuevos_datos['oferta'],
    'tipo_alimentacion': original_nuevos_datos['tipo_alimentacion'] # Esto ya es numérico
})


# Aplicar codificación one-hot a las columnas categóricas relevantes en temp_df_for_ohe
categorical_cols_to_transform = ['estado', 'producto', 'mercado', 'demanda', 'oferta']
temp_df_ohe_result = pd.get_dummies(temp_df_for_ohe, columns=categorical_cols_to_transform, drop_first=True)


# Rellenar 'tipo_alimentacion' codificado con etiquetas
if 'tipo_alimentacion' in nuevos_datos_processed.columns:
    nuevos_datos_processed['tipo_alimentacion'] = original_nuevos_datos['tipo_alimentacion']

# Rellenar características numéricas con los valores medios de los datos de entrenamiento (X para DecisionTreeRegressor)
numerical_features = ['inflacion', 'temperatura', 'ventas']
for col in numerical_features:
    if col in nuevos_datos_processed.columns:
        nuevos_datos_processed[col] = X[col].mean()

# Rellenar columnas codificadas one-hot de temp_df_ohe_result
for col in temp_df_ohe_result.columns:
    if col in nuevos_datos_processed.columns:
        nuevos_datos_processed[col] = temp_df_ohe_result[col].astype(int)

# Asegurar que todas las columnas booleanas sean de tipo entero (1/0) para consistencia, ya que get_dummies puede devolver bool
for col in nuevos_datos_processed.columns:
    if nuevos_datos_processed[col].dtype == 'bool':
        nuevos_datos_processed[col] = nuevos_datos_processed[col].astype(int)

# --- Verificar y Predecir ---
predicciones = modelo.predict(nuevos_datos_processed)

print(predicciones)

importances = modelo.feature_importances_
cols = X.columns

for col, imp in zip(cols, importances):
    print(col, ":", round(imp,3))

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error

# 1. Cargar la base de datos con el nombre real del entorno
df = pd.read_csv("/content/Base_14000_Datos.csv")

# Crear una copia para las transformaciones específicas de Random Forest
df_processed_for_rf = df.copy()

# Preprocesar la columna 'inflacion' para asegurar que sea numérica
# Reemplazar comas por puntos y convertir a numérico, manejando errores
if 'inflacion' in df_processed_for_rf.columns:
    df_processed_for_rf['inflacion'] = df_processed_for_rf['inflacion'].astype(str).str.replace(',', '.', regex=False)
    df_processed_for_rf['inflacion'] = pd.to_numeric(df_processed_for_rf['inflacion'], errors='coerce')

# 2. Preprocesamiento robusto de variables categóricas
# Codificación de etiquetas para 'tipo_alimentacion'
if 'tipo_alimentacion' in df_processed_for_rf.columns and df_processed_for_rf['tipo_alimentacion'].dtype == 'object':
    df_processed_for_rf['tipo_alimentacion'] = df_processed_for_rf['tipo_alimentacion'].astype('category').cat.codes

# Identificar columnas categóricas de texto restantes
categorical_cols_to_encode = []
for col in ['estado', 'producto', 'mercado', 'demanda', 'oferta']:
    if col in df_processed_for_rf.columns and df_processed_for_rf[col].dtype == 'object':
        categorical_cols_to_encode.append(col)

# Aplicar One-Hot Encoding forzando valores numéricos enteros (0 y 1)
if categorical_cols_to_encode:
    df_processed_for_rf = pd.get_dummies(df_processed_for_rf, columns=categorical_cols_to_encode, drop_first=True, dtype=int)

# 3. Segmentación de dimensiones predictoras (X) y objetivo (y)
X = df_processed_for_rf.drop(columns=['precio_kg', 'fecha'])
y = df_processed_for_rf['precio_kg']

# División cronológica/secuencial (shuffle=False es ideal para estructuras con fechas)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False, random_state=42)

# 4. Construcción y entrenamiento del Ensamble (Random Forest)
modelo_rf = RandomForestRegressor(n_estimators=100, random_state=42)
modelo_rf.fit(X_train, y_train)

# 5. Evaluación del rendimiento del modelo
pred = modelo_rf.predict(X_test)
mae = mean_absolute_error(y_test, pred)

print("=========================================")
print(f" ERROR ABSOLUTO MEDIO (MAE): {round(mae, 4)}")
print("=========================================\n")

# 6. Extracción del peso matemático de las variables
importances = modelo_rf.feature_importances_
cols = X.columns

print("--- Importancia de las Características ---")
for col, imp in zip(cols, importances):
    print(f"{col:<30} : {round(imp, 4)}")
print("------------------------------------------\n")

# 7. Simulación predictiva y visualización temporal
futuro = X_test.tail(12)
pred_futuro = modelo_rf.predict(futuro)

plt.figure(figsize=(10, 5))
plt.plot(pred_futuro, marker='o', color='darkred', linestyle='--', label='Precio Predicho')
plt.title("Predicción Futura del Precio de la Carne por kg (Enfoque ML - 2026)")
plt.xlabel("Índice de Muestra Reciente")
plt.ylabel("Precio ($ MXN)")
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/Base_14000_Datos.csv")

# Preprocesar la columna 'inflacion' para asegurar que sea numérica
# Reemplazar comas por puntos y convertir a numérico, manejando errores
if 'inflacion' in df.columns:
    df['inflacion'] = df['inflacion'].astype(str).str.replace(',', '.', regex=False)
    df['inflacion'] = pd.to_numeric(df['inflacion'], errors='coerce')


print("Primeras filas:")
print(df.head())

print("\nInformación de la base:")
print(df.info())


# 1. PRODUCTO


print("\nPromedio de precio por producto:")

producto_precio = df.groupby("producto")["precio_kg"].mean()

print(producto_precio)


# GRÁFICA PRODUCTO


producto_precio.plot(kind="bar")

plt.title("Precio promedio por producto")
plt.xlabel("Producto")
plt.ylabel("Precio por kg")
plt.show()


# 2. PRECIO


print("\nPrecio promedio general:")

precio_promedio = df["precio_kg"].mean()

print(precio_promedio)


# HISTOGRAMA DE PRECIOS


plt.hist(df["precio_kg"], bins=20)

plt.title("Distribución de precios")
plt.xlabel("Precio")
plt.ylabel("Frecuencia")

plt.show()


# 3. PLAZA (MERCADO)


print("\nPrecio promedio por mercado:")

mercado_precio = df.groupby("mercado")["precio_kg"].mean()

print(mercado_precio)


# GRÁFICA DE MERCADO


mercado_precio.plot(kind="bar")

plt.title("Precio promedio por mercado")
plt.xlabel("Mercado")
plt.ylabel("Precio")

plt.show()


# 4. PROMOCIÓN


print("\nVentas promedio por mercado:")

ventas_mercado = df.groupby("mercado")["ventas"].mean()

print(ventas_mercado)


# GRÁFICA DE VENTAS


ventas_mercado.plot(kind="bar")

plt.title("Promedio de ventas por mercado")
plt.xlabel("Mercado")
plt.ylabel("Ventas")

plt.show()


# MERCADO DIGITAL VS TRADICIONAL


digital = df[df["mercado"] == "digital"]["precio_kg"].mean()

tradicional = df[df["mercado"] == "tradicional"]["precio_kg"].mean()

print("\nComparación de mercados:")

print("Mercado digital:", digital)

print("Mercado tradicional:", tradicional)


# ESTADOS CON MÁS VENTAS


top_estados = df.groupby("estado")["ventas"].sum().sort_values(ascending=False)

print("\nEstados con más ventas:")

print(top_estados)


# GRÁFICA TOP ESTADOS


top_estados.plot(kind="bar")

plt.title("Ventas por estado")
plt.xlabel("Estado")
plt.ylabel("Ventas")

plt.show()


# CONCLUSIONES AUTOMÁTICAS


print("\nCONCLUSIONES:")

print("- El producto con mayor precio promedio puede considerarse premium.")

print("- El mercado digital presenta diferencias importantes respecto al tradicional.")

print("- Las ventas permiten identificar mercados con mayor demanda.")

print("- El análisis ayuda a tomar decisiones comerciales y estrategias de marketing.")

import folium

# 1. Crear el mapa base centrado en el corazón de México
mapa_logistico = folium.Map(location=[23.6345, -102.5528], zoom_start=5, tiles="OpenStreetMap")

# 2. Diccionario expandido de Nodos Clave (Coordenadas de los estados de tu información)
nodos_completo = {
    # ORÍGENES / PRODUCTORES (Marcadores Azules)
    "Sonora (Productor Norte)": {"coords": [29.2972, -110.3309], "tipo": "productor", "info": "Cría, Engorda y Control Sanitario (SuKarne)"},
    "Chihuahua (Productor Norte)": {"coords": [28.6330, -106.0691], "tipo": "productor", "info": "Exportación y Engorda de alta calidad"},
    "Veracruz (Productor Golfo)": {"coords": [19.1738, -96.1342], "tipo": "productor", "info": "Principal productor del Golfo, abastece Centro y Sureste"},
    "Tamaulipas (Productor Golfo)": {"coords": [24.2669, -98.8363], "tipo": "productor", "info": "Rastros TIF y enlace al Centro"},
    "Jalisco (Productor Occidente)": {"coords": [20.6597, -103.3496], "tipo": "productor", "info": "Abastece Occidente, Bajío y Centro"},
    "Sinaloa (Productor Occidente)": {"coords": [25.1721, -107.4795], "tipo": "productor", "info": "Producción y engorda intensiva"},

    # CENTROS DE PROCESAMIENTO Y DISTRIBUCIÓN PRINCIPALES (Marcadores Naranjas)
    "Nuevo León (Centro Logístico TIF)": {"coords": [25.2558, -100.0873], "tipo": "procesamiento", "info": "Plantas Empacadoras y Distribución de frío (Sigma Alimentos)"},
    "San Luis Potosí (Grupo Gusi)": {"coords": [22.1565, -100.9855], "tipo": "procesamiento", "info": "Centro de Procesamiento y Clasificación de carne"},

    # DESTINOS / CONSUMO (Marcadores Rojos)
    "CDMX / EdoMex (Consumo Mayoritario)": {"coords": [19.4326, -99.1332], "tipo": "destino", "info": "Central de Abasto, Supermercados y Canales Digitales"},
    "Yucatán (Consumo Sureste)": {"coords": [20.7250, -89.1394], "tipo": "destino", "info": "Punto de llegada de la ruta del Golfo (Veracruz)"}
}

# 3. Dibujar los marcadores personalizados en el mapa
for nombre, datos in nodos_completo.items():
    # Asignar color según la etapa de la cadena de suministro
    if datos["tipo"] == "productor":
        color_icono = "blue"
        icono_tipo = "leaf"
    elif datos["tipo"] == "procesamiento":
        color_icono = "orange"
        icono_tipo = "industry"
    else:
        color_icono = "red"
        icono_tipo = "shopping-cart"

    folium.Marker(
        location=datos["coords"],
        popup=f"<b>{nombre}</b><br>{datos['info']}",
        tooltip=nombre,
        icon=folium.Icon(color=color_icono, icon=icono_tipo, prefix="fa")
    ).add_to(mapa_logistico)

# 4. Dibujar las Rutas Logísticas Principales (Aristas) con la Cadena de Frío
# RUTA 1: Norte -> Centro (Azul)
folium.PolyLine(
    locations=[nodos_completo["Sonora (Productor Norte)"]["coords"], nodos_completo["CDMX / EdoMex (Consumo Mayoritario)"]["coords"]],
    color="darkblue", weight=3, opacity=0.8, tooltip="Ruta Norte-Centro (Sonora -> CDMX)"
).add_to(mapa_logistico)

folium.PolyLine(
    locations=[nodos_completo["Chihuahua (Productor Norte)"]["coords"], nodos_completo["Nuevo León (Centro Logístico TIF)"]["coords"]],
    color="cyan", weight=3, opacity=0.7, tooltip="Ruta de Engorda a Planta TIF"
).add_to(mapa_logistico)

# RUTA 2: Golfo -> Centro y Sureste (Verde)
folium.PolyLine(
    locations=[nodos_completo["Veracruz (Productor Golfo)"]["coords"], nodos_completo["CDMX / EdoMex (Consumo Mayoritario)"]["coords"]],
    color="green", weight=3, opacity=0.8, tooltip="Ruta Golfo-Centro (Veracruz -> CDMX)"
).add_to(mapa_logistico)

folium.PolyLine(
    locations=[nodos_completo["Veracruz (Productor Golfo)"]["coords"], nodos_completo["Yucatán (Consumo Sureste)"]["coords"]],
    color="darkgreen", weight=3, opacity=0.8, tooltip="Ruta Golfo-Sureste (Abastecimiento Regional)"
).add_to(mapa_logistico)

# RUTA 3: Occidente -> Bajío y Centro (Morado)
folium.PolyLine(
    locations=[nodos_completo["Jalisco (Productor Occidente)"]["coords"], nodos_completo["CDMX / EdoMex (Consumo Mayoritario)"]["coords"]],
    color="purple", weight=3, opacity=0.8, tooltip="Ruta Occidente-Centro (Jalisco -> CDMX)"
).add_to(mapa_logistico)

folium.PolyLine(
    locations=[nodos_completo["Sinaloa (Productor Occidente)"]["coords"], nodos_completo["San Luis Potosí (Grupo Gusi)"]["coords"]],
    color="magenta", weight=3, opacity=0.7, tooltip="Ruta de Distribución Occidente-Bajío"
).add_to(mapa_logistico)

# 5. MOSTRAR EN GOOGLE COLAB
mapa_logistico

import folium
import networkx as nx

# 1. Definir los nodos (Estados) y sus coordenadas
nodos = {
    "Sonora": [29.2972, -110.3309],
    "Chihuahua": [28.6330, -106.0691],
    "Tamaulipas": [24.2669, -98.8363],
    "Sinaloa": [25.1721, -107.4795],
    "Jalisco": [20.6597, -103.3496],
    "San Luis Potosí": [22.1565, -100.9855],
    "Veracruz": [19.1738, -96.1342],
    "CDMX": [19.4326, -99.1332]
}

# 2. Definir las conexiones posibles (Aristas) y sus pesos (distancias aproximadas en km)
# Kruskal buscará la combinación más barata/corta de estas opciones
conexiones = [
    ("Sonora", "Chihuahua", 500),
    ("Sonora", "Sinaloa", 620),
    ("Chihuahua", "Sinaloa", 450),
    ("Chihuahua", "San Luis Potosí", 780),
    ("Sinaloa", "Jalisco", 520),
    ("Tamaulipas", "San Luis Potosí", 330),
    ("Tamaulipas", "Veracruz", 700),
    ("Jalisco", "San Luis Potosí", 310),
    ("Jalisco", "CDMX", 540),
    ("San Luis Potosí", "Veracruz", 460),
    ("San Luis Potosí", "CDMX", 420),
    ("Veracruz", "CDMX", 400)
]

# 3. Crear el grafo con NetworkX y aplicar el Algoritmo de Kruskal
G = nx.Graph()

# Añadir aristas con sus pesos
for u, v, peso in conexiones:
    G.add_edge(u, v, weight=peso)

# EJECUCIÓN DE KRUSKAL
arbol_minimo = nx.minimum_spanning_tree(G, algorithm="kruskal")

# 4. Crear el mapa base de Folium
mapa_kruskal = folium.Map(location=[23.6345, -102.5528], zoom_start=5)

# Dibujar todos los nodos (estados)
for estado, coords in nodos.items():
    folium.Marker(
        location=coords,
        popup=estado,
        tooltip=estado,
        icon=folium.Icon(color="red", icon="info-sign")
    ).add_to(mapa_kruskal)

# Dibujar SOLO las aristas que el algoritmo de Kruskal seleccionó como óptimas
print("--- RUTAS ÓPTIMAS SELECCIONADAS POR SUCURSAL ---")
costo_total = 0

for u, v, data in arbol_minimo.edges(data=True):
    peso = data['weight']
    costo_total += peso
    print(f"Ruta: {u} <--> {v} ({peso} km)")

    # Dibujar la línea en el mapa
    folium.PolyLine(
        locations=[nodos[u], nodos[v]],
        color="darkgreen",
        weight=4,
        opacity=0.8,
        tooltip=f"{u} a {v}: {peso} km"
    ).add_to(mapa_kruskal)

print(f"Distancia total de la red optimizada: {costo_total} km\n")

# 5. Mostrar el mapa interactivo en Colab
mapa_kruskal

# Añadiendo un marcador de posición para 'costo_alimento' ya que no estaba presente en el DataFrame.
df['costo_alimento'] = 150  # Puedes ajustar este valor o derivarlo si tienes datos de costos reales.

precio = df['precio_kg'].mean()
costo = df['costo_alimento'].mean()

mejor = 0
mejor_decision = None

for vender in range(50,150):
    ganancia = (precio * vender) - (costo * vender)

    if ganancia > mejor:
        mejor = ganancia
        mejor_decision = vender

print("Cantidad óptima a vender:", mejor_decision)
print("Ganancia:", mejor)

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA

# Cargar los datos (asumiendo que ya leíste el CSV)
df = pd.read_csv('/content/Base_14000_Datos.csv')

# Preprocesar la columna 'inflacion' para asegurar que sea numérica
# Reemplazar comas por puntos y convertir a numérico, manejando errores
if 'inflacion' in df.columns:
    df['inflacion'] = df['inflacion'].astype(str).str.replace(',', '.', regex=False)
    df['inflacion'] = pd.to_numeric(df['inflacion'], errors='coerce')

# 1. Preparar la serie de tiempo
# Convertir la columna fecha a formato datetime
df['fecha'] = pd.to_datetime(df['fecha'])

# Agrupar por fecha, ordenar y establecer la frecuencia diaria
df_ts = df.groupby('fecha')['precio_kg'].mean().sort_index()
df_ts = df_ts.asfreq('D')

# Rellenar los días que no tuvieron transacciones con el último valor conocido
df_ts = df_ts.ffill()

# 2. Definir y entrenar el modelo ARIMA
# (p=5, d=1, q=0) como base
modelo_arima = ARIMA(df_ts, order=(5, 1, 0))
resultados_arima = modelo_arima.fit()

# Imprimir el resumen estadístico del modelo
print(resultados_arima.summary())

# 3. Pronóstico para los próximos 30 días
pasos_futuros = 30
pred_futuro = resultados_arima.forecast(steps=pasos_futuros)

# 4. Visualización
plt.figure(figsize=(12, 6))

# Graficar los últimos 100 días históricos para no saturar la gráfica
plt.plot(df_ts.index[-100:], df_ts.tail(100), label='Precio Histórico Reciente', color='blue')
# Graficar la predicción continua
plt.plot(pred_futuro.index, pred_futuro, color='red', linestyle='--', label='Predicción ARIMA (30 días)')

plt.title("Predicción Futura de Precios (Modelo ARIMA)", fontsize=14)
plt.xlabel("Fecha", fontsize=12)
plt.ylabel("Precio de la carne (Kg)", fontsize=12)
plt.legend()
plt.grid(True, linestyle=':', alpha=0.6)
plt.show()

from statsmodels.tsa.statespace.sarimax import SARIMAX

# Definimos el orden regular (p,d,q) y el orden estacional (P,D,Q,s)
# 's=7' si la estacionalidad es semanal, o 's=12' si los datos fueran mensuales con ciclos anuales.
# Para datos diarios con ciclos semanales:
modelo_sarima = SARIMAX(df_ts, order=(5, 1, 0), seasonal_order=(1, 1, 1, 7))
resultados_sarima = modelo_sarima.fit()

# Predicción
pred_sarima = resultados_sarima.forecast(steps=30)

from statsmodels.tsa.statespace.sarimax import SARIMAX

# Definimos el orden regular (p,d,q) y el orden estacional (P,D,Q,s)
# 's=7' si la estacionalidad es semanal, o 's=12' si los datos fueran mensuales con ciclos anuales.
# Para datos diarios con ciclos semanales:
modelo_sarima = SARIMAX(df_ts, order=(5, 1, 0), seasonal_order=(1, 1, 1, 7))
resultados_sarima = modelo_sarima.fit()

# Predicción
pred_sarima = resultados_sarima.forecast(steps=30)

from prophet import Prophet

# Prophet requiere un DataFrame con columnas específicas: 'ds' y 'y'
df_prophet = df_ts.reset_index()
df_prophet.columns = ['ds', 'y']

# Entrenar el modelo
modelo_prophet = Prophet(yearly_seasonality=True, weekly_seasonality=True)
modelo_prophet.fit(df_prophet)

# Crear un dataframe con las fechas futuras (30 días)
futuro = modelo_prophet.make_future_dataframe(periods=30)
prediccion = modelo_prophet.predict(futuro)

# Visualizar (Prophet tiene sus propias herramientas de gráfica automáticas)
modelo_prophet.plot(prediccion)